[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra
markers =
    ci_mini: Keep the mark
    sanity: Run sanity cases (fast MR gate)
    regression: Run regression cases (nightly)
